version: '3.3'

services:
  web:
    image: dorigomarco0/railsapp:latest
    ports:
      - "3010:3000"
    environment:
      SECRET_KEY_BASE: dummy
      RAILS_ENV: production
    volumes:
      - .:/rails
      - rails_storage:/rails/storage
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      echo '>>> Applicazione disponibile su http://localhost:3010' &&
      bundle exec rails db:prepare &&
      bundle exec rails s -b 0.0.0.0 -p 3000"
    restart: unless-stopped

volumes:
  rails_storage:

