name: Pipeline

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Installazione dipendenze
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev
          bundle install
    
      - name: Preparazione database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create db:migrate RAILS_ENV=test

      - name: Esecuzione test
        run: bundle exec rspec
        env:
            RAILS_ENV: test

